server:
  port: 8088
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/shopclothes_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13082002a
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thunv1308@gmail.com
    password: fkbs xadi agnz hdvm
    properties:
      mail:
        smtp:
          auth: true
          transport:
            protocol: smtp
          starttls:
            enable: true

jwt:
  privateKey: BuyWkVX1rtFgUgIMNDTAmXMfs7t4TbvhZxOJWfULYSQ=

api:
  prefix: api/v1